name: Jovian_helper
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bowtie2==2.3.4.3
  - blast==2.9.0
  - krona==2.7.1
  - mgkit==0.3.4
  - make==4.2.1 # Not installed by default on WSL, needed for Krona db updater
  - awscli
